### ISSUE TITLE
Erroneous rows in biomappings.sssom.tsv? 

### ISSUE THREAD

**Issue by glass-ships** [biopragmatics/biomappings#126]
looking at the [biomappings.sssom.tsv](https://raw.githubusercontent.com/biopragmatics/biomappings/master/docs/_data/sssom/biomappings.sssom.tsv) file in `docs/_data/sssom`, it appears that there are some rows which incorrectly map chemicals to/from diseases, for example:
```
chebi:60411	bacteriopheophytin	skos:exactMatch	mesh:D011470	Prostatic Hyperplasia	semapv:LexicalMatching		0.95	generate_chebi_mesh_mappings.py
```

**Comment by cthoyt** [comment]
The justification is that this is a lexical mapping. Downstream consumers if and how they want to include these. Sssom does not dictate that mappings need to be correct nor high confidence to appear in a given file. For example, you can filter for mappings that have author reviews on them for a high quality set. You can also include explicitly incorrect mappings with the negation predicate modifier column (not in here yet)

**Comment by cthoyt** [comment]
btw @glass-ships I am happy to show you how to do your own curations with the Biomappings frontend to remove incorrect lexical mappings. It might also be the case that we can bulk remove some lexical predictions based on entity types, I would also be keen to accept a PR with a script to help do that

**Comment by glass-ships** [comment]
> btw I am happy to show you how to do your own curations with the Biomappings frontend to remove incorrect lexical mappings. 

That would be fantastic! I'd even be happy to help contribute to such a PR if it overlaps for sure

**Comment by glass-ships** [comment]
hey @cthoyt would you be open to a brief zoom meeting going over how to do such a curation? 
(if so, my schedule is fairly open, just let me know what works for you! feel free to reach out via Slack)

**Comment by cthoyt** [comment]
@glass-ships yes! I actually went to make a tutorial video today but got distracted by some bugs that needed fixing. if you're on west coast USA time then the best slot is 8AM or 9AM for you and late afternoon for me some time later this week like Thursday

**Comment by glass-ships** [comment]
oh no worries! afternoon thursday sounds perfect

**Comment by cthoyt** [comment]
@glass-ships you can check https://youtu.be/shZ4OpRInF0 in the mean time - are you on the OBO Foundry slack? it would be great if you wanted to join there and we can more quickly chat https://join.slack.com/t/obo-communitygroup/shared_invite/zt-1wt9fc739-TjteCXRot4oagW4FvrEKGA

**Comment by glass-ships** [comment]
thanks @cthoyt !! The video is super well made, I'd love to see more actually! 
I'm still a bit curious how we could make the curation process a bit more automated though?
(I've joined the slack in the meantime, thanks for linking!)
