### ISSUE TITLE
Published SSSOM mapping set is not compliant with SSSOM TSV specification

### ISSUE THREAD

**Issue by gouttegd** [biopragmatics/biomappings#154]
The SSSOM TSV file (docs/_data/sssom/biomappings.sssom.tsv) and its associated metadata YML file (docs/_data/sssom/biomappings.sssom.yml) are not valid according to the SSSOM specification:

1) Invalid use of `mapping_set_group`.

The `mapping_set_group` slot is only allowed on a [MappingSetReference](https://mapping-commons.github.io/sssom/MappingSetReference/) class, _not_ in the [MappingSet](https://mapping-commons.github.io/sssom/MappingSet/) class.

2) Use of non-declared prefixes.

Some prefixes used are undeclared: cvx, orcid, RO, kegg.pathway

The spec says “The YAML metadata block MUST contain a curie map that allows the unambiguous interpretation of CURIES”, which SSSOM-Java interprets as a requirement for _all_ prefix names to be explicitly declared in said map (otherwise there is always room for “ambiguous interpretation”),  the only exception being the “built-in” prefixes: `sssom`, `owl`, `rdf`, `rdfs`, `skos`, `semapv`.

**Comment by cthoyt** [comment]
Thanks for the feedback! On it.

**Comment by cthoyt** [comment]
@gouttegd should be good now, let me know if there are other hiccups (I can foresee conflict between bioregistry standard prefixes and OBO flavored prefixes being an issue, I am already thinking about this)

**Comment by gouttegd** [comment]
All good, thanks. :)

Well, at least from the SSSOM point-of-view. Because you’re absolutely right that this:

```
curie_map:
  […]
  uberon: 'https://www.ebi.ac.uk/ols4/ontologies/uberon/terms?obo_id=UBERON:'
```

_will_ be an issue when it will come to translate mappings into OWL axioms.
