### ISSUE TITLE
Neoplasms

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/biomappings#43]
umls	C0006142	Malignant neoplasm of breast	skos:exactMatch	mesh	D001943	Breast Neoplasms	manual	orcid:0000-0003-4423-4370

Can't  be exact if the latter encompasses non malignant eg carcinoma in situ. I recommend getting these from mondo

**Comment by cthoyt** [comment]
Good catch, now I have to extend the data model to include information about review ;)

**Comment by cmungall** [comment]
If only there were a data model and tsv format for mappings that could be
adopted :-)

**Comment by cthoyt** [comment]
I have an SSSOM exporter somewhere that I wrote for Nico... better figure out why it isn't more prominent in the repo that there's an export of it
